spring.application.name=gerenciamento

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/gerenciamento?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=040621FaFa$
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

security.token.jwt.secret=${SECURITY_JWT_SECRET:TESTE55}
security.token.jwt.expiration=${SECURITY_JWT_EXPIRATION:8}